### ISSUE TITLE
Validate that the Crimeflare DB is really useful

### ISSUE THREAD

**Issue by SageHack** [SageHack/cloud-buster#15]
The Crimeflare database has not been updated since I first downloaded it on May 2015. A lot of results simply timeout, don't exists or don't even use Cloudflare. Some IPs do match.

I am starting to think that most IPs that matches could be resolved properly by the tool. That might take a bit longer while scanning but it would mean less code and also not having to download the Crimeflare DB locally.

**Comment by SageHack** [comment]
After scanning [domains-25.txt](https://github.com/SageHack/cloud-buster/files/1815676/domains-25.txt) with [crimeflare only scan](https://github.com/SageHack/cloud-buster/files/1815669/bust_domains25_crimeflare.txt) and with [comprehensive scan](https://github.com/SageHack/cloud-buster/files/1815668/bust_domains25_comprehensive.txt) it looks like Crimeflare is just an MX resolver. All match from Crimeflare are match from the MX scan technique.

Some matches are invalid as the current matching technique is a bit buggy and need reworking. I'll have to test it again once #8 #9 #12 #13 are fixed.

**Comment by SageHack** [comment]
Here's the [result of ipout-filter.sh](https://github.com/SageHack/cloud-buster/files/1815787/ipout-protected.txt)

**Comment by SageHack** [comment]
Following the [1.3](https://github.com/SageHack/cloud-buster/releases/tag/1.3) second matching engine overhaul, it's now possible to finish this analysis.

**Comment by SageHack** [comment]
Here's my study in numbers:
* Crimeflare DB has **666 745** entries
* **128 960** entries host a working service "behind" Cloudflare

Testing the first **4059** entries from "working sites" list:
* **823** (20%) origins confirmed using only the Crimeflare DB
* **1335** (32%) origins confirmed, scanning MX and the `direct.` subdomain
* **263** (6%) origins were confirmed exclusively by using the Crimeflare DB.
* **129** (49%) of the exclusive matches confirmed by scanning top 200 subdomains.

If we assume that those numbers are representative, it mean:
* at most, **3%** of the origins would not match without it
* **20%** of the origins can be confirmed without falling back to other scan techniques

It's also important to consider that:
* The comprehensive scan will match even more origins
* The DB doesn't look like it's updated so it's significance will decrease over time
* As for pen-testing purpose, it doesn't help fixing your app security issues
* This feature is irrelevant for testing other CDN/WAF services

My final verdict: **Should be removed.**

**Comment by m0rtem** [comment]
I would recommend keeping it as an option (maybe not included with default scan) as it may be useful for historical data. If an IP has been found in that database, it means somewhere it has been logged. So even if that IP does not resolve to anything, we could in theory use a service such as domaintools.com to find the history behind the host. 

IDK, it seems like it could be a useful identifier, Id like to play around with historical records more as I think that is the key to finding the true host.

**Comment by SageHack** [comment]
I've decided to favor in @m0rtem 's opinion

Still, I've made some changes to optimize script performance and repo weight a bit:
* 4bfae79f6d48434ba191f22bf6fc8b841fb6d99c Removed domains not hosted behind Cloudflare anymore
* 953bc2a284594238fb31e7e513ea20fb94d21048 Update.py will not download ipout.zip anymore since we confirmed there was no updates for at least 3 years
* aece86e40b589693318217ab5c4896836ce343c8 Load the file in memory so it's not read for each domain when scanning lists

Should we need to recover the full DB for any reason, we can `git checkout 303a5c9434490e897b4624de134b601e26d18ba2 lists/ipout && git mv lists/ipout crimeflare/db`
