### ISSUE TITLE
Investigate CloudFail

### ISSUE THREAD

**Issue by SageHack** [SageHack/cloud-buster#16]
Check if there's a technique used by https://github.com/m0rtem/CloudFail that could benefit the CloudBuster, or simply merge both software together. IDK.

**Comment by m0rtem** [comment]
All it does at the moment is:

1. Misconfigured DNS scan using DNSDumpster.com.
2. Scan the Crimeflare.com database.
3. Bruteforce scan over 2500 subdomains.

So at the moment it is not much different than yours- I do however have a whitepaper somewhere which I was writing which in theory was going to turn into CloudFail V2 with many new methods and less false positives. Id like to explore these methods a bit more before releasing to public (the methods are public, but you know, people are lazy)

more to come

**Comment by SageHack** [comment]
@m0rtem 
1. dnsdumpster.com looks fun. I'll check that out.
2. I started doing some heavy research there on #15 but I still need to get #9 done before I can keep moving.
About false positive: I have a few ideas and I'm starting to get some test data I can work with. This is pretty much #9 here. So far my validation technique isn't as great as I thought.

I don't have many more ideas to add here though. Can't wait to see what you have in mind. Also, if we get some work done I guess I'm up for a teamed rebrand ;) FailBuster I guess Xp

**Comment by SageHack** [comment]
Two other nifty features that CloudFail has over CloudBuster is nifty colors (make things easier to see honestly) and `--tor`.

**Comment by SageHack** [comment]
dnsDumpster is worth integrating. #23 created to that end.

**Comment by SageHack** [comment]
I've pretty much added all cool features from CloudFail as issues in this project. Closing this.
