### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by shibumi** [SageHack/cloud-buster#4]
Hello could you use pleas release-tags? I want to package this package for the Archlinux User repository so people can easily search for it and install it on the fly.

Would be great. 

cheers

chris

**Comment by SageHack** [comment]
Here you go :)

https://github.com/SageHack/cloud-buster/releases

Let me know once it's package I'll add the information on the github
repo and on my website.

That's pretty cool by the way thanks :)

**Comment by shibumi** [comment]
Hello,
Sorry for the delay. I have created 2 versions. Version 1 is the stable version (using git tags).
Version 2 is the unstable developer version (using your current git head in master)

https://aur.archlinux.org/packages/cloud-buster/
https://aur.archlinux.org/packages/cloud-buster-git/

greetings

Chris

**Comment by SageHack** [comment]
That is absolutely cool! How do you install package on Arch? And,
dependencies are Python3 and theres a python module to install too, just
to be sure.

**Comment by shibumi** [comment]
@sagehack
python3 is called in archlinux python python2 is python2 :)

to the modules.

Which modules do I need exactly? you are shipping the most of your modules in your directory.

**Comment by SageHack** [comment]
Just one :

pip3 install dnspython3
