### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by NovaCygni** [SageHack/cloud-buster#7]
Anyway we can work to update this to also work with Blazingfast aswell as its a similar based VPS to Cloudflare, If so feel free to message me and we can work on it, seems a  resolver isnt out yet for it so we could get a first :)

**Comment by SageHack** [comment]
Hi @NovaCygni Sorry about this late reply. I was offline for more than 6 months. I have a lot of stuff to do at the moment but I plan to work on this project at a later than and I would love to add more CDN support like Fastly, CloudFront and whit not BlazingFast. I'll let you know where I'm there.
